#!/usr/bin/env python3
"""
Interactive devices.xml / scanner.xml generator for OpenRFStack nodes.

Walks through adding one or more SDR devices (with sensible PlutoSDR/RTL-SDR
presets you can accept or override) and a sweep frequency range, then writes
devices.xml (and patches scanner.xml's sweep range) into one of the
deploy/<node-type>/configs/ directories, or to a custom path for mounting at
runtime with -v /path/to/devices.xml:/etc/sdr/devices.xml:ro,z.

Usage:
    ./configure_devices.py
"""
import os
import shutil
import sys

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
NODE_TYPES = ["sdr-node", "mobile-node", "recon-node"]

PRESETS = {
    "pluto": {
        "label": "PlutoSDR",
        "driver": "plutosdr",
        "uri": "",
        "uri_hint": "leave empty to auto-discover via USB scan or zeroconf/mDNS",
        "rx_channels": 2, "tx_channels": 2,
        "freq_min_mhz": 70.0, "freq_max_mhz": 6000.0,
        "bandwidth_max_mhz": 20.0, "sample_rate_max_msps": 61.44,
        "rx_gain_min_db": -3, "rx_gain_max_db": 71,
    },
    "rtlsdr": {
        "label": "RTL-SDR",
        "driver": "rtlsdr",
        "uri": "driver=rtlsdr",
        "uri_hint": "SoapyRTLSDR ignores this beyond the driver= key",
        "rx_channels": 1, "tx_channels": 0,
        "freq_min_mhz": 0.5, "freq_max_mhz": 1700.0,
        "bandwidth_max_mhz": 3.2, "sample_rate_max_msps": 3.2,
        "rx_gain_min_db": 0, "rx_gain_max_db": 49,
    },
    "custom": {
        "label": "", "driver": "", "uri": "", "uri_hint": "",
        "rx_channels": 1, "tx_channels": 0,
        "freq_min_mhz": 0.0, "freq_max_mhz": 0.0,
        "bandwidth_max_mhz": 0.0, "sample_rate_max_msps": 0.0,
        "rx_gain_min_db": 0, "rx_gain_max_db": 0,
    },
}

DEVICES_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  SdrResourceManager device config — generated by configure_devices.py
  Override at runtime: -v /path/to/devices.xml:/etc/sdr/devices.xml:ro,z
-->
<sdr_controller version="2.0">

  <broker>
    <url>amqp://localhost:5672</url>
    <username>sdr_ctrl</username>
    <password>sdr_hw_test</password>
    <request_queue>sdr.task.request</request_queue>
    <response_queue>sdr.task.response</response_queue>
    <status_topic>sdr.status</status_topic>
    <health_topic>sdr.health</health_topic>
    <reconnect_interval_sec>5</reconnect_interval_sec>
    <max_reconnect_interval_sec>30</max_reconnect_interval_sec>
    <send_queue_depth>512</send_queue_depth>
  </broker>

  <policy>
    <max_concurrent_tasks>4</max_concurrent_tasks>
    <guard_band_hz>200000</guard_band_hz>
    <usable_bw_fraction>0.80</usable_bw_fraction>
    <default_task_timeout_ms>120000</default_task_timeout_ms>
    <scheduler_tick_ms>200</scheduler_tick_ms>
    <watchdog_tick_ms>1000</watchdog_tick_ms>
    <udp_port_pool_start>30000</udp_port_pool_start>
    <udp_port_pool_end>30099</udp_port_pool_end>
    <iq_packet_samples>256</iq_packet_samples>
    <retune_conflict_policy>REJECT_NEW</retune_conflict_policy>
    <heartbeat_interval_ms>10000</heartbeat_interval_ms>
  </policy>

  <devices>
{devices_xml}
  </devices>

</sdr_controller>
"""

DEVICE_TEMPLATE = """    <device id="{id}">
      <driver>{driver}</driver>
      <uri>{uri}</uri>
      <label>{label}</label>
      <streaming_source_ip>127.0.0.1</streaming_source_ip>
      <capabilities>
        <rx_channels>{rx_channels}</rx_channels>
        <tx_channels>{tx_channels}</tx_channels>
        <freq_min_hz>{freq_min_hz}</freq_min_hz>
        <freq_max_hz>{freq_max_hz}</freq_max_hz>
        <bandwidth_max_hz>{bandwidth_max_hz}</bandwidth_max_hz>
        <sample_rate_max_sps>{sample_rate_max_sps}</sample_rate_max_sps>
        <rx_gain_min_db>{rx_gain_min_db}</rx_gain_min_db>
        <rx_gain_max_db>{rx_gain_max_db}</rx_gain_max_db>
      </capabilities>
    </device>"""


def ask(prompt, default=None):
    suffix = f" [{default}]" if default is not None else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val if val else default


def ask_float(prompt, default):
    while True:
        raw = ask(prompt, str(default))
        try:
            return float(raw)
        except ValueError:
            print("  Please enter a number.")


def ask_int(prompt, default):
    while True:
        raw = ask(prompt, str(default))
        try:
            return int(raw)
        except ValueError:
            print("  Please enter a whole number.")


def ask_choice(prompt, choices, default_idx=0):
    print(prompt)
    for i, c in enumerate(choices, 1):
        marker = " (default)" if i - 1 == default_idx else ""
        print(f"  {i}) {c}{marker}")
    while True:
        raw = input(f"Choice [1-{len(choices)}]: ").strip()
        if not raw:
            return default_idx
        if raw.isdigit() and 1 <= int(raw) <= len(choices):
            return int(raw) - 1
        print("  Invalid choice.")


def configure_device(existing_ids):
    idx = ask_choice(
        "\nDevice type:",
        ["PlutoSDR (network or USB)", "RTL-SDR (USB)", "Custom / other SoapySDR driver"],
    )
    preset_key = ["pluto", "rtlsdr", "custom"][idx]
    preset = PRESETS[preset_key]

    default_id = preset_key if preset_key != "custom" else "sdr"
    n = 0
    while f"{default_id}-{n}" in existing_ids:
        n += 1
    dev_id = ask("Device id", f"{default_id}-{n}")

    driver = preset["driver"] if preset_key != "custom" else ask("SoapySDR driver name (e.g. plutosdr, rtlsdr, lime, uhd)", "")
    label = ask("Label", preset["label"] or driver)
    if preset["uri_hint"]:
        print(f"  uri hint: {preset['uri_hint']}")
    uri = ask("uri (leave empty for discovery)", preset["uri"])

    print("Capabilities (Enter to accept preset/default):")
    rx_channels = ask_int("  RX channels", preset["rx_channels"])
    tx_channels = ask_int("  TX channels", preset["tx_channels"])
    freq_min_mhz = ask_float("  Min frequency (MHz)", preset["freq_min_mhz"])
    freq_max_mhz = ask_float("  Max frequency (MHz)", preset["freq_max_mhz"])
    bandwidth_max_mhz = ask_float("  Max instantaneous bandwidth (MHz)", preset["bandwidth_max_mhz"])
    sample_rate_max_msps = ask_float("  Max sample rate (MSPS)", preset["sample_rate_max_msps"])
    rx_gain_min_db = ask_int("  RX gain min (dB)", preset["rx_gain_min_db"])
    rx_gain_max_db = ask_int("  RX gain max (dB)", preset["rx_gain_max_db"])

    return DEVICE_TEMPLATE.format(
        id=dev_id, driver=driver, uri=uri, label=label,
        rx_channels=rx_channels, tx_channels=tx_channels,
        freq_min_hz=int(freq_min_mhz * 1e6), freq_max_hz=int(freq_max_mhz * 1e6),
        bandwidth_max_hz=int(bandwidth_max_mhz * 1e6),
        sample_rate_max_sps=int(sample_rate_max_msps * 1e6),
        rx_gain_min_db=rx_gain_min_db, rx_gain_max_db=rx_gain_max_db,
    ), dev_id


def patch_scanner_sweep(scanner_path, start_hz, stop_hz):
    if not os.path.isfile(scanner_path):
        print(f"  (no scanner.xml at {scanner_path} — skipping sweep range patch)")
        return
    with open(scanner_path) as f:
        text = f.read()
    import re
    text, n1 = re.subn(r"<start_hz>\d+</start_hz>", f"<start_hz>{start_hz}</start_hz>", text)
    text, n2 = re.subn(r"<stop_hz>\d+</stop_hz>", f"<stop_hz>{stop_hz}</stop_hz>", text)
    if n1 == 0 or n2 == 0:
        print(f"  (couldn't find <start_hz>/<stop_hz> in {scanner_path} — skipping)")
        return
    shutil.copy2(scanner_path, scanner_path + ".bak")
    with open(scanner_path, "w") as f:
        f.write(text)
    print(f"  Patched {scanner_path} (backup at {scanner_path}.bak)")


def main():
    print("OpenRFStack device config generator\n")

    devices_xml_parts = []
    existing_ids = set()
    while True:
        device_xml, dev_id = configure_device(existing_ids)
        devices_xml_parts.append(device_xml)
        existing_ids.add(dev_id)
        if ask_choice("\nAdd another device?", ["No", "Yes"], default_idx=0) == 0:
            break

    print("\nSweep frequency range (used by scanner.xml if you choose to patch it):")
    start_mhz = ask_float("  Start (MHz)", 80.0)
    stop_mhz = ask_float("  Stop (MHz)", 1000.0)
    start_hz, stop_hz = int(start_mhz * 1e6), int(stop_mhz * 1e6)

    devices_xml = DEVICES_TEMPLATE.format(devices_xml="\n\n".join(devices_xml_parts))

    print("\nWhere should this be written?")
    target_idx = ask_choice(
        "",
        [f"deploy/{t}/configs/ (overwrites that node type's defaults)" for t in NODE_TYPES]
        + ["Custom path (for mounting with -v at runtime)"],
        default_idx=0,
    )

    if target_idx < len(NODE_TYPES):
        node_dir = os.path.join(REPO_ROOT, "deploy", NODE_TYPES[target_idx], "configs")
        devices_path = os.path.join(node_dir, "devices.xml")
        scanner_path = os.path.join(node_dir, "scanner.xml")
    else:
        devices_path = ask("Output path for devices.xml", os.path.join(REPO_ROOT, "devices.xml"))
        scanner_path = None

    if os.path.isfile(devices_path):
        if ask_choice(f"\n{devices_path} already exists. Overwrite?", ["No", "Yes"], default_idx=0) == 0:
            print("Aborted — nothing written.")
            return
        shutil.copy2(devices_path, devices_path + ".bak")
        print(f"  Backed up existing file to {devices_path}.bak")

    os.makedirs(os.path.dirname(devices_path), exist_ok=True)
    with open(devices_path, "w") as f:
        f.write(devices_xml)
    print(f"\nWrote {devices_path}")

    if scanner_path:
        if ask_choice(f"Patch {scanner_path}'s sweep range to {start_mhz}-{stop_mhz} MHz too?",
                      ["Yes", "No"], default_idx=0) == 0:
            patch_scanner_sweep(scanner_path, start_hz, stop_hz)

    print("\nDone.")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nAborted.")
        sys.exit(1)
